import { memo, useEffect, useRef, useState } from "react";
import { roomManager } from "./RoomManager";
import { useRuntimeEditorStore } from "./runtimeEditorStore";
import { downloadWorldJson, isGameWorldData } from "./worldPersistence";
import type { GameSceneData, MapObjectData, RoomData, RoomType, WorldAssetData } from "./worldTypes";
import "./developerEditor.css";

const BUILTIN_ASSETS = [
  { id: "hub-map", name: "Hub ground", source: "/assets/hub/hub1.png", type: "ground", width: 1315, height: 1196 },
  { id: "market-map", name: "Market ground", source: "/assets/hub/market.png", type: "ground", width: 1728, height: 1024 },
  { id: "archive-map", name: "Archive ground", source: "/assets/hub/archive.png", type: "building", width: 1024, height: 1536 },
  { id: "arena-map", name: "Arena ground", source: "/assets/hub/arena.png", type: "ground", width: 1728, height: 1024 },
] as const satisfies ReadonlyArray<Omit<WorldAssetData, "importedAt">>;
const EDITOR_ENABLED = import.meta.env.DEV || import.meta.env.VITE_ENABLE_RUNTIME_EDITOR === "true";
const SHADERS = { none: "none", soft: "saturate(.9) contrast(1.04)", moonlight: "brightness(.78) saturate(.65) hue-rotate(12deg)", warm: "sepia(.18) saturate(1.2)", ghost: "grayscale(.35) brightness(1.25)" } as const;

function slug(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, ""); }
function emptyRoom(id: string, name: string, input?: Partial<RoomData>): RoomData {
  return { id, name, width: 1280, height: 720, gridSize: 16, roomType: "outdoor", backgroundColor: "#081224", objects: [], colliders: [], portals: [], spawnPoints: [{ id: "default", name: "Default spawn", position: { x: 640, y: 360 }, facing: "down" }], ...input };
}
function currentRoom(world: ReturnType<typeof useRuntimeEditorStore.getState>["world"], sceneId: string, roomId: string) {
  return world.scenes.find((scene) => scene.id === sceneId)?.rooms.find((room) => room.id === roomId);
}
function objectFilter(preset?: string) { return SHADERS[preset as keyof typeof SHADERS] ?? SHADERS.none; }

function SceneRoomTree({ onCreateScene, onCreateRoom }: { onCreateScene: () => void; onCreateRoom: () => void }) {
  const world = useRuntimeEditorStore((state) => state.world); const sceneId = useRuntimeEditorStore((state) => state.currentSceneId); const roomId = useRuntimeEditorStore((state) => state.currentRoomId);
  return <section className="devPanel devTree"><header><span>Scenes and Rooms</span><button onClick={onCreateScene}>+ Scene</button></header><div className="devTreeScroll">{world.scenes.map((scene) => <div className="devScene" key={scene.id}><div className="devSceneTitle"><strong>▾ {scene.name}</strong><button onClick={() => roomManager.loadScene(scene.id)}>Open</button></div>{scene.rooms.map((room) => <button key={room.id} className={`devRoom ${sceneId === scene.id && roomId === room.id ? "is-active" : ""}`} onClick={() => roomManager.loadRoom(scene.id, room.id)}><i>{sceneId === scene.id && roomId === room.id ? "●" : "○"}</i><span>{room.name}<small>{room.id} · {room.width}×{room.height} · {room.colliders.length} colliders</small></span></button>)}</div>)}</div><button className="devWideButton" onClick={onCreateRoom} disabled={!sceneId}>+ Create room</button></section>;
}

function AssetLibrary() {
  const world = useRuntimeEditorStore((state) => state.world); const placeObject = useRuntimeEditorStore((state) => state.placeObject); const updateRoom = useRuntimeEditorStore((state) => state.updateRoom);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const assets = [...BUILTIN_ASSETS, ...(world.assets ?? [])]; const filtered = assets.filter((asset) => asset.name.toLowerCase().includes(search.toLowerCase()));
  const place = (asset: typeof assets[number]) => placeObject({ id: `object_${crypto.randomUUID()}`, assetId: asset.source, name: asset.name, type: asset.type, position: { x: 640, y: 360 }, scale: { x: 1, y: 1 }, rotation: 0, flipX: false, flipY: false, width: Math.min(asset.width, 320), height: Math.min(asset.height, 320), sortingLayer: "world", sortingOrder: 1, opacity: 1, tint: "#ffffff", visible: true, locked: false, shaderPreset: "none", metadata: { castShadow: false } });
  const importPng = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) return setStatus("Choose a PNG or WebP image."); const reader = new FileReader(); reader.onload = () => { if (typeof reader.result !== "string") return; const image = new Image(); image.onload = () => { useRuntimeEditorStore.getState().addAsset({ id: `custom_${crypto.randomUUID()}`, name: file.name.replace(/\.[^.]+$/, ""), source: reader.result as string, type: "customSprite", width: image.naturalWidth, height: image.naturalHeight, importedAt: new Date().toISOString() }); setStatus(`${file.name} imported (${image.naturalWidth}×${image.naturalHeight})`); }; image.src = reader.result; }; reader.readAsDataURL(file); };
  return <section className="devPanel devAssets"><header><span>Asset Library</span><button onClick={() => inputRef.current?.click()}>Import PNG</button></header><input ref={inputRef} hidden type="file" accept="image/png,image/webp" onChange={(event) => importPng(event.target.files?.[0])} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search textures and sprites" /><div className="devAssetGrid">{filtered.map((asset) => <article key={asset.id}><img src={asset.source} alt="" /><span>{asset.name}</span><div><button onClick={() => place(asset)}>Place</button><button title="Use as room background" onClick={() => updateRoom({ metadata: { ...(currentRoom(useRuntimeEditorStore.getState().world, useRuntimeEditorStore.getState().currentSceneId, useRuntimeEditorStore.getState().currentRoomId)?.metadata ?? {}), backgroundAsset: asset.source } })}>BG</button></div></article>)}</div><small>{status || "Place as sprite or set as the room background."}</small></section>;
}

function NumberField({ label, value, onChange, step = 1 }: { label: string; value: number; onChange: (value: number) => void; step?: number }) { return <label>{label}<input type="number" step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function SelectionInspector() {
  const world = useRuntimeEditorStore((state) => state.world); const sceneId = useRuntimeEditorStore((state) => state.currentSceneId); const roomId = useRuntimeEditorStore((state) => state.currentRoomId); const selectedId = useRuntimeEditorStore((state) => state.selectedObjectId); const updateObject = useRuntimeEditorStore((state) => state.updateObject); const deleteObject = useRuntimeEditorStore((state) => state.deleteObject); const updateRoom = useRuntimeEditorStore((state) => state.updateRoom);
  const room = currentRoom(world, sceneId, roomId); const object = room?.objects.find((item) => item.id === selectedId);
  if (!room) return null;
  if (!object) return <aside className="devInspector devPanel"><header>Room Inspector</header><div className="devInspectorBody"><label>Background color<input type="color" value={room.backgroundColor} onChange={(event) => updateRoom({ backgroundColor: event.target.value })} /></label><div className="devFormRow"><NumberField label="Width" value={room.width} onChange={(width) => updateRoom({ width })} /><NumberField label="Height" value={room.height} onChange={(height) => updateRoom({ height })} /></div><button onClick={() => updateRoom({ metadata: { ...room.metadata, backgroundAsset: undefined } })}>Clear background texture</button><small>Choose Place or BG in the Asset Library.</small></div></aside>;
  const patchPosition = (axis: "x" | "y", value: number) => updateObject(object.id, { position: { ...object.position, [axis]: value } });
  const castShadow = object.metadata?.castShadow === true;
  return <aside className="devInspector devPanel"><header><span>Object Inspector</span><button onClick={() => deleteObject(object.id)}>Delete</button></header><div className="devInspectorBody"><strong>{object.name}</strong><div className="devFormRow"><NumberField label="X" value={Math.round(object.position.x)} onChange={(value) => patchPosition("x", value)} /><NumberField label="Y" value={Math.round(object.position.y)} onChange={(value) => patchPosition("y", value)} /></div><div className="devFormRow"><NumberField label="Width" value={object.width ?? 100} onChange={(width) => updateObject(object.id, { width })} /><NumberField label="Height" value={object.height ?? 100} onChange={(height) => updateObject(object.id, { height })} /></div><div className="devFormRow"><NumberField label="Rotation" value={object.rotation} onChange={(rotation) => updateObject(object.id, { rotation })} /><NumberField label="Opacity" value={object.opacity} step={.05} onChange={(opacity) => updateObject(object.id, { opacity: Math.max(0, Math.min(1, opacity)) })} /></div><label>Shader preset<select value={object.shaderPreset ?? "none"} onChange={(event) => updateObject(object.id, { shaderPreset: event.target.value })}>{Object.keys(SHADERS).map((shader) => <option key={shader}>{shader}</option>)}</select></label><label className="devCheck"><input type="checkbox" checked={castShadow} onChange={(event) => updateObject(object.id, { metadata: { ...object.metadata, castShadow: event.target.checked } })} /> Cast soft shadow</label><label className="devCheck"><input type="checkbox" checked={object.locked} onChange={(event) => updateObject(object.id, { locked: event.target.checked })} /> Lock object</label><small>Drag the object directly on the map. Position is snapped to the room grid.</small></div></aside>;
}

function EditorTopBar({ onImport }: { onImport: () => void }) { const world = useRuntimeEditorStore((state) => state.world); const dirty = useRuntimeEditorStore((state) => state.isDirty); return <div className="devTopBar"><strong>FRAKTUM <b>MAP EDITOR</b></strong><span className={dirty ? "is-dirty" : ""}>{dirty ? "Unsaved changes" : "Saved locally"}</span><div /><button onClick={() => useRuntimeEditorStore.getState().saveWorld()}>Save</button><button onClick={() => downloadWorldJson(world)}>Export JSON</button><button onClick={onImport}>Import JSON</button><button className="devPlay" onClick={() => useRuntimeEditorStore.getState().setMode("play")}>▶ Play</button></div>; }

function CreateModal({ kind, close }: { kind: "scene" | "room"; close: () => void }) { const sceneId = useRuntimeEditorStore((state) => state.currentSceneId); const [name, setName] = useState(kind === "scene" ? "New Scene" : "New Room"); const [id, setId] = useState(kind === "scene" ? "new_scene" : "new_room"); const [width, setWidth] = useState(1280); const [height, setHeight] = useState(720); const [roomType, setRoomType] = useState<RoomType>("outdoor"); const [error, setError] = useState(""); const submit = (event: React.FormEvent) => { event.preventDefault(); const safeId = slug(id); if (!safeId) return setError("A valid unique ID is required."); const room = emptyRoom(kind === "scene" ? "main" : safeId, kind === "scene" ? "Main Room" : name.trim(), { width, height, roomType }); if (kind === "scene") { const scene: GameSceneData = { id: safeId, name: name.trim(), defaultRoomId: room.id, backgroundColor: "#081224", rooms: [room] }; if (!useRuntimeEditorStore.getState().createScene(scene)) return setError("Scene ID already exists."); } else if (!useRuntimeEditorStore.getState().createRoom(sceneId, room)) return setError("Room ID already exists."); close(); }; return <div className="devModalBackdrop" onMouseDown={close}><form className="devModal" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><header>Create {kind}</header><label>Name<input value={name} onChange={(event) => { setName(event.target.value); setId(slug(event.target.value)); }} /></label><label>ID<input value={id} onChange={(event) => setId(event.target.value)} /></label><div className="devFormRow"><NumberField label="Width" value={width} onChange={setWidth} /><NumberField label="Height" value={height} onChange={setHeight} /></div><label>Room type<select value={roomType} onChange={(event) => setRoomType(event.target.value as RoomType)}><option>outdoor</option><option>indoor</option><option>dungeon</option><option>special</option></select></label>{error && <p>{error}</p>}<footer><button type="button" onClick={close}>Cancel</button><button type="submit">Create</button></footer></form></div>; }

const RuntimeMapObject = memo(function RuntimeMapObject({ object, selected, gridSize }: { object: MapObjectData; selected: boolean; gridSize: number }) {
  const select = useRuntimeEditorStore((state) => state.selectObject); const update = useRuntimeEditorStore((state) => state.updateObject); const dragRef = useRef<{ x: number; y: number; start: MapObjectData["position"] } | null>(null);
  const down = (event: React.PointerEvent<HTMLImageElement>) => { event.stopPropagation(); select(object.id); if (object.locked || useRuntimeEditorStore.getState().mode !== "edit") return; event.currentTarget.setPointerCapture(event.pointerId); dragRef.current = { x: event.clientX, y: event.clientY, start: object.position }; };
  const move = (event: React.PointerEvent<HTMLImageElement>) => { const drag = dragRef.current; if (!drag) return; const map = event.currentTarget.closest(".hubMapLayer"); const scale = map ? map.getBoundingClientRect().width / map.clientWidth : 1; const snap = (value: number) => Math.round(value / gridSize) * gridSize; update(object.id, { position: { x: snap(drag.start.x + (event.clientX - drag.x) / scale), y: snap(drag.start.y + (event.clientY - drag.y) / scale) } }); };
  return <img className={`runtimeMapObject ${selected ? "is-selected" : ""} ${object.metadata?.castShadow === true ? "has-shadow" : ""}`} src={object.assetId} alt={object.name} draggable={false} onPointerDown={down} onPointerMove={move} onPointerUp={() => { dragRef.current = null; }} style={{ left: object.position.x, top: object.position.y, width: object.width, height: object.height, opacity: object.opacity, zIndex: object.sortingOrder, filter: `${objectFilter(object.shaderPreset)} ${object.metadata?.castShadow === true ? "drop-shadow(10px 14px 9px rgba(0,0,0,.58))" : ""}`, transform: `translate(-50%, -50%) rotate(${object.rotation}deg) scale(${object.scale.x * (object.flipX ? -1 : 1)}, ${object.scale.y * (object.flipY ? -1 : 1)})` }} />;
});
export const RoomObjectLayer = memo(function RoomObjectLayer() { const world = useRuntimeEditorStore((state) => state.world); const sceneId = useRuntimeEditorStore((state) => state.currentSceneId); const roomId = useRuntimeEditorStore((state) => state.currentRoomId); const selected = useRuntimeEditorStore((state) => state.selectedObjectId); const room = currentRoom(world, sceneId, roomId); return <>{room?.objects.filter((object) => object.visible).map((object) => <RuntimeMapObject key={object.id} object={object} selected={selected === object.id} gridSize={room.gridSize || 1} />)}</>; });

export default function DeveloperEditor() { const mode = useRuntimeEditorStore((state) => state.mode); const [modal, setModal] = useState<"scene" | "room" | null>(null); const fileRef = useRef<HTMLInputElement>(null); useEffect(() => { if (!EDITOR_ENABLED) return; const key = (event: KeyboardEvent) => { if (event.key === "F10") { event.preventDefault(); useRuntimeEditorStore.getState().toggleEditor(); } if (event.ctrlKey && event.key.toLowerCase() === "s" && mode === "edit") { event.preventDefault(); useRuntimeEditorStore.getState().saveWorld(); } if (event.key === "Delete" && mode === "edit") { const id = useRuntimeEditorStore.getState().selectedObjectId; if (id) useRuntimeEditorStore.getState().deleteObject(id); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [mode]); const importFile = async (file?: File) => { if (!file) return; const parsed: unknown = JSON.parse(await file.text()); if (isGameWorldData(parsed)) useRuntimeEditorStore.getState().replaceWorld(parsed); }; if (!EDITOR_ENABLED || mode !== "edit") return null; return <div className="developerEditor"><EditorTopBar onImport={() => fileRef.current?.click()} /><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={(event) => void importFile(event.target.files?.[0])} /><div className="devLeftRail"><SceneRoomTree onCreateScene={() => setModal("scene")} onCreateRoom={() => setModal("room")} /><AssetLibrary /></div><SelectionInspector /><div className="devStatus">Drag sprites · Delete removes · F10 play · Ctrl+S save</div>{modal && <CreateModal kind={modal} close={() => setModal(null)} />}</div>; }
