import type { GameAction } from "../core/GameAction";
import type { CardDefinition, CardInstance, MatchState, PlayerId, StartMatchPayload, TargetRef } from "../core/types";
import { loadCardDefinitions } from "../data/cards";
import { runSimpleAI } from "../ai/SimpleAI";
import { resolveCardEffects } from "./EffectResolver";
import { rollDie } from "./Random";
import { canPayWill, gainWillFromRoll, payWill } from "./WillSystem";
const other = (p: PlayerId): PlayerId => (p === "player" ? "enemy" : "player");
const inst = (d: CardDefinition, ownerId: PlayerId, n: number): CardInstance => ({ instanceId: `${ownerId}_${d.id}_${n}`, baseId: d.id, definition: d, currentAttack: d.attack, currentHealth: d.health, ownerId });
function log(s: MatchState, m: string): MatchState { return { ...s, log: [...s.log, m].slice(-50) }; }
function makeSide(id: PlayerId, defs: CardDefinition[]) { const heroDef = defs.find((c) => c.type === "character") ?? loadCardDefinitions()[0]; const all = defs.filter((c) => c.id !== heroDef.id).map((d, i) => inst(d, id, i)); const bonusCards = all.filter((c) => c.definition.type === "bonus"); const deck = all.filter((c) => c.definition.type !== "bonus"); const hero = inst(heroDef, id, 999); return { id, hero, hp: heroDef.health || 30, maxHp: heroDef.health || 30, shield: 0, will: 0, maxWill: 5, deck: deck.slice(5), hand: deck.slice(0, 5), discard: [], bonusCards, effects: [], lastTurnLostHp: 0 }; }
export function createInitialMatchState(payload: StartMatchPayload = {}): MatchState { const defs = loadCardDefinitions(); const playerDeck = payload.playerDeck ?? defs; const enemyDeck = payload.enemyDeck ?? defs.map((c) => c.id === "brian" ? (defs.find((d) => d.id === "felix") ?? c) : c); return { id: `match_${Date.now()}`, phase: "roll", turn: 1, activePlayerId: "player", player: makeSide("player", playerDeck), enemy: makeSide("enemy", enemyDeck), board: { playerSlots: Array(5).fill(null), enemySlots: Array(5).fill(null) }, stack: [], log: ["React TypeScript match started."], rngSeed: payload.seed ?? 12345 }; }
export const startMatch = createInitialMatchState;
export function dispatch(state: MatchState, action: GameAction): MatchState { try { if (state.phase === "ended" && action.type !== "START_MATCH") return log(state, "Match already ended."); switch (action.type) { case "START_MATCH": return startMatch(action.payload); case "ROLL_D20": return rollD20(state, action.playerId); case "PLAY_CARD": return playCard(state, action.playerId, action.cardInstanceId, action.target); case "END_TURN": return endTurn(state, action.playerId); case "AI_TURN": return runSimpleAI(state); case "CONCEDE": return log({ ...state, phase: "ended", winner: other(action.playerId) }, `${action.playerId} conceded.`); } } catch (error) { return log(state, `Invalid action: ${error instanceof Error ? error.message : String(error)}`); } }
export function rollD20(state: MatchState, playerId: PlayerId): MatchState { if (state.activePlayerId !== playerId) return log(state, `It is not ${playerId}'s roll.`); const r = rollDie(state.rngSeed, 20); return log({ ...state, rngSeed: r.seed, lastRoll: r.value, phase: playerId === "player" ? "main" : "enemy", [playerId]: gainWillFromRoll(state[playerId], r.value) }, `${playerId} rolled D20: ${r.value} and gained Will.`); }
export function playCard(state: MatchState, playerId: PlayerId, cardInstanceId: string, _target?: TargetRef): MatchState { if (state.activePlayerId !== playerId) return log(state, `It is not ${playerId}'s turn.`); const side = state[playerId]; const card = side.hand.find((c) => c.instanceId === cardInstanceId); if (!card) return log(state, "Card is not in hand."); if (!canPayWill(side, card.definition.cost)) return log(state, `${card.definition.title} needs ${card.definition.cost} Will.`); let next: MatchState = { ...state, [playerId]: { ...payWill(side, card.definition.cost), hand: side.hand.filter((c) => c.instanceId !== cardInstanceId) } };
  next = resolveCardEffects(next, playerId, card); const slotsKey = playerId === "player" ? "playerSlots" : "enemySlots"; if (card.definition.type === "character") { const slots = [...next.board[slotsKey]]; const empty = slots.findIndex((s) => !s); if (empty >= 0) slots[empty] = card; next = { ...next, board: { ...next.board, [slotsKey]: slots } }; } else { next = { ...next, [playerId]: { ...next[playerId], discard: [...next[playerId].discard, card] } }; } return checkWinCondition(log(next, `${playerId} played ${card.definition.title}.`)); }
export function endTurn(state: MatchState, playerId: PlayerId): MatchState { if (state.activePlayerId !== playerId) return log(state, `It is not ${playerId}'s turn.`); const next = other(playerId); return log({ ...state, activePlayerId: next, phase: next === "player" ? "roll" : "enemy", turn: playerId === "enemy" ? state.turn + 1 : state.turn, [next]: { ...state[next], lastTurnLostHp: 0 } }, `${playerId} ended turn.`); }
export function checkWinCondition(state: MatchState): MatchState { if (state.player.hp <= 0 && state.enemy.hp <= 0) return { ...state, phase: "ended", winner: "draw" }; if (state.player.hp <= 0) return { ...state, phase: "ended", winner: "enemy" }; if (state.enemy.hp <= 0) return { ...state, phase: "ended", winner: "player" }; return state; }
