import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
const cardsSource = readFileSync(new URL('../src/data/cards.json', import.meta.url), 'utf8');
const adapterSource = readFileSync(new URL('../src/game/data/cards.ts', import.meta.url), 'utf8');
const engineSource = readFileSync(new URL('../src/game/engine/MatchEngine.ts', import.meta.url), 'utf8');
const cardViewSource = readFileSync(new URL('../src/components/match/CardView.tsx', import.meta.url), 'utf8');
const handViewSource = readFileSync(new URL('../src/components/match/HandView.tsx', import.meta.url), 'utf8');
const enemyHandSource = readFileSync(new URL('../src/components/match/EnemyHandView.tsx', import.meta.url), 'utf8');
for (const required of ['energy_sword', 'reverse_heart', 'caduceus', 'crystal_of_time', 'phoenix_feather']) assert(cardsSource.includes(required), `missing ${required}`);
assert(adapterSource.includes('CARDS.map(toEngineCardDefinition)'), 'engine cards must be adapted from src/data/cards.json');
assert(engineSource.includes('temporaryUntilRoundEnd: !permanent'), 'no-HP cards must be marked temporary');
assert(engineSource.includes('cleanupTemporaryCards'), 'round cleanup must exist');
assert(engineSource.includes('Not enough Will'), 'insufficient Will log must exist');
assert(engineSource.includes('No-card penalty'), 'no-card penalty log must exist');
assert(cardViewSource.includes('matchCardBadge is-cost'), 'card cost badge missing');
assert(cardViewSource.includes('matchCardBadge is-hp'), 'card HP badge missing');
assert(handViewSource.includes('onPointerDown') && handViewSource.includes('elementsFromPoint'), 'pointer drag/drop missing');
assert(enemyHandSource.includes('enemyCardBack'), 'enemy card back class missing');
console.log('Fallback game checks passed (Vitest package unavailable in this environment).');
