using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public enum MatchPhase { StartTurn, Draw, RollDice, Main, Resolve, EndTurn }

[RequireComponent(typeof(MatchManager))]
public class MatchUIController : MonoBehaviour
{
    public MatchManager Manager { get; private set; }
    public HandFanController playerHand; public OpponentHandView opponentHand; public ResourceController playerResource; public ResourceController enemyResource; public DiceView diceView; public CombatResolver combat; public EffectResolver effects;
    public Text playerInfo, enemyInfo, phaseText, logText, timerText; public Button endTurnButton; public GameObject resultPanel; public Text resultText; public RectTransform discardPile, activeEffects, resolutionZone; public CardView runtimeCardPrefab;
    public MatchPhase phase; public bool enemyWeakened; private int turn=1; private float timer=75f;

    private void Awake(){ Manager=GetComponent<MatchManager>(); BuildRuntimeBoard(); combat=gameObject.AddComponent<CombatResolver>(); effects=gameObject.AddComponent<EffectResolver>(); effects.ui=this; effects.combat=combat; }
    private IEnumerator Start(){ yield return null; EnsureFallbackDecks(); playerHand.SetCards(Manager.playerState.hand); opponentHand.SetCardCount(Manager.aiState.hand.Count); StartPlayerTurn(); }
    private void Update(){ if(phase==MatchPhase.Main){ timer-=Time.deltaTime; if(timerText) timerText.text=Mathf.CeilToInt(timer).ToString(); if(timer<=0) EndPlayerTurn(); } }
    public void StartPlayerTurn(){ phase=MatchPhase.StartTurn; turn++; timer=75; DrawCard(Manager.playerState,true); playerResource.StartTurn(turn); phase=MatchPhase.RollDice; diceView.Roll(); phase=MatchPhase.Main; RefreshAll(); Log("Ваш ход: доберите, бросьте d20 и играйте карты."); }
    public void EndPlayerTurn(){ if(phase!=MatchPhase.Main) return; StartCoroutine(AITurn()); }
    private IEnumerator AITurn(){ phase=MatchPhase.StartTurn; RefreshAll(); Log("Ход противника..."); yield return new WaitForSeconds(.5f); DrawCard(Manager.aiState,false); enemyResource.StartTurn(turn); yield return new WaitForSeconds(.5f); if(!enemyWeakened){ CardInstance pick=Manager.aiState.hand.Find(c=>c.definition!=null && c.definition.willCost<=enemyResource.current); if(pick!=null){ enemyResource.Spend(pick.definition.willCost); Manager.aiState.hand.Remove(pick); Log("Противник играет: "+pick.definition.cardName+". "+effects.Resolve(pick,false)); Manager.aiState.graveyard.Add(pick); }} else { Log("Противник ослаблен и пропускает активное действие."); enemyWeakened=false; } yield return new WaitForSeconds(.8f); StartPlayerTurn(); }
    public bool TryPlayPlayerCard(CardView card, DropZone zone){ if(phase!=MatchPhase.Main || card?.Instance?.definition==null) return false; int cost=card.Instance.definition.willCost; if(!playerResource.Spend(cost)){ Log("Недостаточно Will для "+card.Instance.definition.cardName); card.SetState(CardViewState.NotEnoughResource); return false;} Manager.playerState.hand.Remove(card.Instance); StartCoroutine(ResolvePlayerCard(card)); return true; }
    private IEnumerator ResolvePlayerCard(CardView card){ phase=MatchPhase.Resolve; RectTransform rt=card.transform as RectTransform; rt.SetParent(resolutionZone, true); Vector3 start=rt.localPosition; for(float t=0;t<1;t+=Time.deltaTime*4){ rt.localPosition=Vector3.Lerp(start,Vector3.zero,Mathf.SmoothStep(0,1,t)); rt.localRotation=Quaternion.identity; rt.localScale=Vector3.one*Mathf.Lerp(1.2f,1.45f,t); yield return null;} string msg=effects.Resolve(card.Instance,true); Log("Вы играете: "+card.Instance.definition.cardName+". "+msg); bool stays=card.Instance.definition.type=="effect"; if(stays){ rt.SetParent(activeEffects,true); rt.localScale=Vector3.one*.72f; } else { Manager.playerState.graveyard.Add(card.Instance); playerHand.RemoveCard(card); } phase=MatchPhase.Main; RefreshAll(); CheckGameOver(); }
    public void DrawCard(PlayerState state,bool player){ if(state.deck.Count>0 && state.hand.Count<MatchManager.HandLimit){ CardInstance c=state.deck[0]; state.deck.RemoveAt(0); state.hand.Add(c); if(player && playerHand!=null) playerHand.AddCard(c); } RefreshAll(); }
    public void DiscardRandom(PlayerState state,bool opponentVisual){ if(state.hand.Count==0) return; int i=Random.Range(0,state.hand.Count); CardInstance c=state.hand[i]; state.hand.RemoveAt(i); state.graveyard.Add(c); RefreshAll(); }
    private void CheckGameOver(){ if(Manager.playerState.HP<=0 || Manager.aiState.HP<=0){ bool won=Manager.aiState.HP<=0; Manager.EndMatch(won); if(resultPanel) resultPanel.SetActive(true); if(resultText) resultText.text=won?"VICTORY\nRewards: essence + pack progress":"DEFEAT\nTry again"; phase=MatchPhase.EndTurn; } }
    private void RefreshAll(){ if(Manager.playerState==null||Manager.aiState==null) return; playerResource.Set(Manager.playerState.Will=playerResource.current, playerResource.maximum); enemyResource.Set(Manager.aiState.Will=enemyResource.current, enemyResource.maximum); if(playerInfo) playerInfo.text=$"{Manager.playerState.playerName}\nHP {Manager.playerState.HP}  Shield {combat.playerShield}\nDeck {Manager.playerState.deck.Count} / Discard {Manager.playerState.graveyard.Count}"; if(enemyInfo) enemyInfo.text=$"{Manager.aiState.playerName}\nRank: Rift Adept\nHP {Manager.aiState.HP}  Shield {combat.enemyShield}\nDeck {Manager.aiState.deck.Count} / Discard {Manager.aiState.graveyard.Count}"; if(phaseText) phaseText.text=phase.ToString(); if(opponentHand) opponentHand.SetCardCount(Manager.aiState.hand.Count); }
    private void Log(string s){ if(logText) logText.text=s+"\n"+logText.text; Debug.Log(s); }
    private void EnsureFallbackDecks(){ if(Manager.playerState.deck.Count+Manager.playerState.hand.Count==0) BuildFallback(Manager.playerState,"P"); if(Manager.aiState.deck.Count+Manager.aiState.hand.Count==0) BuildFallback(Manager.aiState,"AI"); for(int i=0;i<5;i++){ DrawCard(Manager.playerState,true); DrawCard(Manager.aiState,false);} }
    private void BuildFallback(PlayerState state,string prefix){ for(int i=0;i<18;i++){ CardDefinition d=ScriptableObject.CreateInstance<CardDefinition>(); d.id=prefix+"_"+i; d.cardName=(i%5==0?"Caduceus Heal":i%4==0?"Old Sage Shield":i%3==0?"Book Knowledge":"Shadow Sword"); d.type=i%5==0?"bonus":i%4==0?"tactic":"attack"; d.rarity=i%3==0?"rare":"common"; d.willCost=1+i%4; d.baseAttack=2+i%3; d.baseHealth=3; d.effectKey=i%5==0?"heal":i%4==0?"shield":i%3==0?"draw":"damage"; d.description="Fallback action for autonomous Unity scene."; state.deck.Add(new CardInstance(d.id,d.id,d)); } }
    private Text MakeText(string name,Transform p,int size,TextAnchor a){ GameObject go=new GameObject(name,typeof(RectTransform),typeof(Text)); go.transform.SetParent(p,false); Text t=go.GetComponent<Text>(); t.font=Resources.GetBuiltinResource<Font>("Arial.ttf"); t.fontSize=size; t.alignment=a; t.color=new Color(.96f,.87f,.68f); return t; }
    private Image Panel(string name,Transform p,Vector2 min,Vector2 max,Color c){ GameObject go=new GameObject(name,typeof(RectTransform),typeof(Image)); go.transform.SetParent(p,false); RectTransform rt=go.GetComponent<RectTransform>(); rt.anchorMin=min; rt.anchorMax=max; rt.offsetMin=rt.offsetMax=Vector2.zero; Image img=go.GetComponent<Image>(); img.color=c; return img; }
    private void BuildRuntimeBoard(){ Canvas canvas=FindObjectOfType<Canvas>(); if(canvas==null){ GameObject cg=new GameObject("FRAKTUM Match Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)); canvas=cg.GetComponent<Canvas>(); canvas.renderMode=RenderMode.ScreenSpaceOverlay; cg.GetComponent<CanvasScaler>().uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize; cg.GetComponent<CanvasScaler>().referenceResolution=new Vector2(1920,1080);} Panel("Dark Fantasy Board",canvas.transform,Vector2.zero,Vector2.one,new Color(.035f,.025f,.055f,1)); runtimeCardPrefab=new GameObject("Runtime CardView",typeof(RectTransform),typeof(CanvasGroup),typeof(CardView)).GetComponent<CardView>(); runtimeCardPrefab.transform.SetParent(transform,false); runtimeCardPrefab.gameObject.SetActive(true);
        Image enemy=Panel("Opponent Zone",canvas.transform,new Vector2(.12f,.73f),new Vector2(.88f,.98f),new Color(.08f,.04f,.11f,.78f)); enemyInfo=MakeText("Enemy Name Rank HP",enemy.transform,22,TextAnchor.MiddleLeft); enemyInfo.rectTransform.anchorMin=new Vector2(.02f,.05f); enemyInfo.rectTransform.anchorMax=new Vector2(.28f,.95f); enemyInfo.rectTransform.offsetMin=enemyInfo.rectTransform.offsetMax=Vector2.zero;
        Image center=Panel("Central Drop Field",canvas.transform,new Vector2(.18f,.28f),new Vector2(.82f,.72f),new Color(.12f,.08f,.16f,.45f)); DropZone dz=center.gameObject.AddComponent<DropZone>(); dz.highlightImage=center; resolutionZone=center.rectTransform; activeEffects=Panel("Active Effects",center.transform,new Vector2(.34f,.03f),new Vector2(.66f,.25f),new Color(.24f,.14f,.34f,.35f)).rectTransform;
        Image player=Panel("Player Zone",canvas.transform,new Vector2(.08f,.02f),new Vector2(.92f,.28f),new Color(.06f,.035f,.08f,.84f)); playerInfo=MakeText("Player HP",player.transform,22,TextAnchor.MiddleLeft); playerInfo.rectTransform.anchorMin=new Vector2(.02f,.05f); playerInfo.rectTransform.anchorMax=new Vector2(.22f,.95f); playerInfo.rectTransform.offsetMin=playerInfo.rectTransform.offsetMax=Vector2.zero;
        GameObject handGo=new GameObject("Player Hand Fan",typeof(RectTransform)); handGo.transform.SetParent(canvas.transform,false); RectTransform hrt=handGo.GetComponent<RectTransform>(); hrt.anchorMin=new Vector2(.5f,.03f); hrt.anchorMax=new Vector2(.5f,.03f); hrt.sizeDelta=new Vector2(900,240); playerHand=handGo.AddComponent<HandFanController>(); playerHand.cardPrefab=runtimeCardPrefab; playerHand.handRoot=hrt;
        GameObject oh=new GameObject("Opponent Hidden Hand",typeof(RectTransform)); oh.transform.SetParent(canvas.transform,false); RectTransform ort=oh.GetComponent<RectTransform>(); ort.anchorMin=new Vector2(.5f,.91f); ort.anchorMax=new Vector2(.5f,.91f); ort.sizeDelta=new Vector2(650,150); opponentHand=oh.AddComponent<OpponentHandView>(); opponentHand.cardBackPrefab=runtimeCardPrefab; opponentHand.handRoot=ort;
        playerResource=CreateResource(canvas.transform,"Player Will",new Vector2(.88f,.07f)); enemyResource=CreateResource(canvas.transform,"Enemy Will",new Vector2(.9f,.78f)); diceView=CreateDice(canvas.transform); phaseText=MakeText("Phase",canvas.transform,24,TextAnchor.MiddleCenter); phaseText.rectTransform.anchorMin=new Vector2(.43f,.93f); phaseText.rectTransform.anchorMax=new Vector2(.57f,.99f); phaseText.rectTransform.offsetMin=phaseText.rectTransform.offsetMax=Vector2.zero; timerText=MakeText("Timer",canvas.transform,28,TextAnchor.MiddleCenter); timerText.rectTransform.anchorMin=new Vector2(.02f,.46f); timerText.rectTransform.anchorMax=new Vector2(.1f,.56f); timerText.rectTransform.offsetMin=timerText.rectTransform.offsetMax=Vector2.zero; logText=MakeText("Battle Log",canvas.transform,16,TextAnchor.UpperLeft); logText.rectTransform.anchorMin=new Vector2(.01f,.12f); logText.rectTransform.anchorMax=new Vector2(.18f,.42f); logText.rectTransform.offsetMin=logText.rectTransform.offsetMax=Vector2.zero;
        GameObject b=new GameObject("End Turn Button",typeof(RectTransform),typeof(Image),typeof(Button)); b.transform.SetParent(canvas.transform,false); endTurnButton=b.GetComponent<Button>(); RectTransform br=b.GetComponent<RectTransform>(); br.anchorMin=new Vector2(.84f,.42f); br.anchorMax=new Vector2(.98f,.5f); br.offsetMin=br.offsetMax=Vector2.zero; b.GetComponent<Image>().color=new Color(.45f,.24f,.08f,.92f); Text bt=MakeText("Label",b.transform,22,TextAnchor.MiddleCenter); bt.text="END TURN"; bt.rectTransform.anchorMin=Vector2.zero; bt.rectTransform.anchorMax=Vector2.one; bt.rectTransform.offsetMin=bt.rectTransform.offsetMax=Vector2.zero; endTurnButton.onClick.AddListener(EndPlayerTurn);
        resultPanel=Panel("Result Panel",canvas.transform,new Vector2(.34f,.32f),new Vector2(.66f,.68f),new Color(.02f,.01f,.03f,.95f)).gameObject; resultText=MakeText("Result Text",resultPanel.transform,34,TextAnchor.MiddleCenter); resultText.rectTransform.anchorMin=Vector2.zero; resultText.rectTransform.anchorMax=Vector2.one; resultText.rectTransform.offsetMin=resultText.rectTransform.offsetMax=Vector2.zero; resultPanel.SetActive(false);
    }
    private ResourceController CreateResource(Transform p,string n,Vector2 anchor){ Image img=Panel(n,p,anchor,anchor,new Color(.22f,.08f,.35f,.9f)); RectTransform rt=img.rectTransform; rt.sizeDelta=new Vector2(118,118); ResourceController rc=img.gameObject.AddComponent<ResourceController>(); rc.label=MakeText("Value",img.transform,20,TextAnchor.MiddleCenter); rc.label.rectTransform.anchorMin=Vector2.zero; rc.label.rectTransform.anchorMax=Vector2.one; rc.label.rectTransform.offsetMin=rc.label.rectTransform.offsetMax=Vector2.zero; rc.resourceName="Will"; return rc; }
    private DiceView CreateDice(Transform p){ Image img=Panel("d20 Dice",p,new Vector2(.02f,.05f),new Vector2(.1f,.15f),new Color(.16f,.08f,.25f,.9f)); DiceView dv=img.gameObject.AddComponent<DiceView>(); dv.resultText=MakeText("d20 Result",img.transform,22,TextAnchor.MiddleCenter); dv.resultText.rectTransform.anchorMin=Vector2.zero; dv.resultText.rectTransform.anchorMax=Vector2.one; dv.resultText.rectTransform.offsetMin=dv.resultText.rectTransform.offsetMax=Vector2.zero; return dv; }
}
